In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('data.csv')

In [14]:
df.sample(10)

,End Date,USD/INR,USD/PKR,USD/CNY,USD/KWD,USD/AED,USD/LKR,USD/CHF,USD/EUR,USD/ALL,...,USD/BMD,USD/BTN,USD/BOB,USD/BAM,USD/BWP,USD/BRL,USD/BND,USD/BGN,USD/BIF,USD/CVE
3506,2010-08-08,46.2500,84.6925,6.76830,0.286120,3.67330,112.380,1.038920,0.752970,102.6900,...,1.00000,45.9655,6.95375,1.74755,6.70200,1.75920,1.33810,1.47237,"1,217.40",82.8530
1818,2005-12-24,45.1350,59.7904,8.07590,0.292125,3.67300,101.905,1.311860,0.842538,102.9330,...,1.00503,45.0600,8.00000,1.51317,5.49842,2.31500,1.66385,1.65004,998.785,93.1505
3705,2011-02-23,45.4129,85.2687,6.57605,0.279320,3.67300,110.746,0.936320,0.729187,101.3980,...,1.00000,45.1244,7.00331,1.73462,6.72733,1.67142,1.27557,1.42435,"1,230.05",80.4378
5268,2015-06-05,63.9898,102.5490,6.11028,0.302155,3.67298,134.863,0.936945,0.893999,125.6070,...,1.00000,63.9915,6.94777,NaN,10.03100,3.14818,1.35465,1.74857,"1,577.98",98.3628
4842,2014-04-05,59.8990,98.1052,6.17547,0.282080,3.67310,130.524,0.892250,0.729677,101.9790,...,1.00000,60.0855,6.91031,NaN,8.81868,2.23587,1.26421,1.42692,"1,549.05",80.4545
2423,2007-08-21,41.1050,60.5244,7.58979,0.281860,3.67300,112.082,1.204830,0.741906,90.1495,...,1.00273,44.3700,7.76345,1.48956,6.32771,2.03345,1.52875,1.45085,"1,109.95",82.2620
2350,2007-06-09,41.1700,60.6650,7.65610,0.288070,3.67270,110.893,1.235090,0.747758,92.8425,...,1.00273,44.3700,7.98600,1.50924,6.35137,1.96710,1.53809,1.46215,"1,065.20",82.3535
1801,2005-12-07,46.1983,59.7985,8.07693,0.292045,3.67295,101.976,1.307510,0.848533,104.4430,...,1.00503,46.0500,8.02000,1.59664,5.49394,2.17961,1.68785,1.66635,999.249,93.9561
2157,2006-11-28,44.6950,60.7452,7.84520,0.289185,3.67302,108.001,1.206270,0.760725,94.7150,...,1.00273,44.3700,7.99440,1.36200,6.12704,2.19090,1.54739,1.48778,"1,043.74",84.4945
48,2001-02-18,46.5150,58.6250,8.27741,0.306525,3.67305,86.500,1.676900,1.093550,143.0000,...,0.99005,46.5174,6.45550,1.57640,5.51893,2.00400,1.73950,2.11340,734.067,114.0050

In [15]:
df.shape

(5892, 36)

In [16]:
df.head(10)

,End Date,USD/INR,USD/PKR,USD/CNY,USD/KWD,USD/AED,USD/LKR,USD/CHF,USD/EUR,USD/ALL,...,USD/BMD,USD/BTN,USD/BOB,USD/BAM,USD/BWP,USD/BRL,USD/BND,USD/BGN,USD/BIF,USD/CVE
0,2001-01-01,46.665,57.850,8.27782,0.305600,3.67300,82.840,1.61080,1.06159,142.45,...,0.985149,46.6808,6.375,1.62173,5.36482,1.95000,1.73230,2.05875,734.067,118.514
1,2001-01-02,46.690,58.650,8.27831,0.304877,3.67300,82.550,1.60076,1.05210,142.45,...,0.990050,46.6808,6.375,1.62722,5.36196,1.94250,1.73570,2.05875,734.067,117.254
2,2001-01-03,46.700,58.150,8.27772,0.305474,3.67300,82.650,1.63058,1.07656,140.84,...,0.990050,46.6808,6.375,1.62722,5.30790,1.93005,1.73120,2.17830,734.067,116.266
3,2001-01-04,46.730,58.900,8.27852,0.305197,3.67300,82.700,1.60628,1.05247,140.00,...,0.990050,46.6808,6.395,1.62722,5.31071,1.94190,1.73280,2.04624,734.067,116.511
4,2001-01-05,46.705,59.100,8.27792,0.305093,3.67300,83.125,1.59790,1.04390,140.65,...,0.990050,46.6808,6.375,1.62722,5.31636,1.95490,1.73450,2.04624,734.067,115.739
5,2001-01-06,46.710,59.275,8.27792,0.305135,3.67290,83.050,1.59790,1.04608,140.65,...,0.990050,46.6808,6.375,1.62722,5.31636,1.95540,1.72990,2.04624,734.067,115.739
6,2001-01-07,46.710,59.275,8.27792,0.304840,3.67290,83.050,1.59800,1.04468,140.65,...,0.990050,46.6808,6.375,1.62722,5.31636,1.95540,1.72990,2.06135,734.067,115.739
7,2001-01-08,46.675,59.150,8.27821,0.305319,3.67300,82.900,1.60655,1.05408,140.00,...,0.990050,46.4473,6.410,1.62722,5.36196,1.94905,1.72970,2.06135,734.067,114.005
8,2001-01-09,46.625,58.575,8.27752,0.305340,3.67284,82.850,1.61283,1.05826,140.90,...,0.990050,46.4473,6.410,1.62722,5.38217,1.94350,1.73255,2.07535,734.067,117.216
9,2001-01-10,46.625,58.550,8.27731,0.305500,3.67284,82.950,1.62850,1.06699,140.60,...,0.990050,46.4473,6.420,1.62722,5.47950,1.94300,1.73550,2.05269,734.067,117.228

In [17]:
len(df)

5892